name: shelf_cors
version: 0.3.0
author: George Moschovitis <george.moschovitis@gmail.com>
description: Middleware to add CORS headers to shelf responses.
homepage: https://github.com/gmosx/dart-shelf_cors
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  shelf: '>=0.6.1 <0.8.0'
dev_dependencies:
  test: any
