name: shelf_cors
version: 0.2.1
author: George Moschovitis <george.moschovitis@gmail.com>
description: Middleware to add CORS headers to shelf responses.
homepage: https://github.com/gmosx/dart-shelf_cors
dependencies:
  shelf: '>=0.6.1 <0.7.0'
dev_dependencies:
  unittest: any
